#################################################################################
# Licensed to the .NET Foundation under one or more agreements.                 #
# The .NET Foundation licenses this file to you under the MIT license.          #
# See the LICENSE file in the project root for more information.                #
#################################################################################
parameters:
  - name: symbolsFolder
    type: string
    default: symbols

  - name: softwareFolder
    type: string
    default: software

  - name: publishSymbols
    type: boolean

jobs:
- job: build_signed_akv_package
  displayName: 'Build Signed AKV Provider Package'
  pool:
    type: windows  # read more about custom job pool types at https://aka.ms/obpipelines/yaml/jobs
    
  variables:
  - template: ../../../libraries/variables.yml@self

  steps:
  - script: SET
    displayName: 'Print Environment Variables'

  - template: ../steps/build-all-configurations-signed-dlls-step.yml@self
    parameters:
      product: AKV
      nugetPackageRefVersion: $(MDS_PackageRef_Version)
      AssemblyFileVersion: $(AKVAssemblyFileVersion)

  - template: ../steps/code-analyze-step.yml@self
    parameters:
      analyzeType: all
      product: AKV
      nugetPackageRefVersion: $(MDS_PackageRef_Version)

  - template: ../steps/esrp-code-signing-step.yml@self
    parameters:
      artifactType: dll

  - template: ../steps/generate-nuget-package-step.yml@self
    parameters:
      OutputDirectory: $(artifactDirectory)
      nuspecPath: ${{variables.akvNuspecPath }}
      NugetPackageVersion: ${{variables.AKVNuGetPackageVersion }}
      referenceType: package

  - template: ../steps/esrp-code-signing-step.yml@self
    parameters:
      artifactType: pkg

  - template: ../steps/copy-dlls-for-test-step.yml@self
    parameters:
      product: AKV
      referenceType: package

  # Publish symbols to servers
  - template: ../steps/publish-symbols-step.yml@self
    parameters:
      referenceType: package
      symbolsVersion: ${{variables.AKVNuGetPackageVersion }}
      product: AKV
      publishSymbols: ${{ parameters['PublishSymbols'] }}
      symbolsArtifactName: akv_symbols_$(System.TeamProject)_$(Build.Repository.Name)_$(Build.SourceBranchName)_$(NuGetPackageVersion)_$(System.TimelineId)
